# Generated by Django 4.2.11 on 2026-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_article_title_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.TextField(choices=[('wikipedia', 'Wikipedia'), ('wikidata', 'Wikidata')], default='wikipedia'),
        ),
        migrations.AddField(
            model_name='edit',
            name='qualifiers_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='qualifiers_modified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='references_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='references_modified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='statements_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='statements_modified',
            field=models.IntegerField(default=0),
        ),
    ]
