# Generated by Django 5.1 on 2026-08-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('contests', '0004_contest_contest_type_edit_qualifiers_created_and_more'), ('contests', '0005_contest_qualifiers_per_points_and_more'), ('contests', '0006_edit_tags'), ('contests', '0007_remove_contest_contest_type'), ('contests', '0008_remove_edit_qualifiers_created_and_more')]

    dependencies = [
        ('contests', '0003_alter_article_title_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='qualifiers_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='references_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='statements_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_qualifiers_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_qualifiers_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_references_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_references_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_statements_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_statements_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='edit',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='EditWikidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statements_created', models.IntegerField(default=0)),
                ('statements_modified', models.IntegerField(default=0)),
                ('references_created', models.IntegerField(default=0)),
                ('references_modified', models.IntegerField(default=0)),
                ('qualifiers_created', models.IntegerField(default=0)),
                ('qualifiers_modified', models.IntegerField(default=0)),
                ('edit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editwikidata', to='contests.edit')),
            ],
            options={
                'verbose_name_plural': 'EditsWikidata',
            },
        ),
    ]
