# Generated by Django 4.2.11 on 2026-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_contest_type_edit_qualifiers_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='qualifiers_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='references_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='statements_per_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_qualifiers_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_qualifiers_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_references_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_references_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_statements_created',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='real_statements_modified',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
