# Generated by Django 4.2.11 on 2026-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_qualifiers_per_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
