# Generated by Django 4.2.11 on 2026-08-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_edit_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_type',
        ),
    ]
