# Generated by Django 4.2.11 on 2026-08-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_remove_contest_contest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='qualifiers_created',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='qualifiers_modified',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='references_created',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='references_modified',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='statements_created',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='statements_modified',
        ),
        migrations.CreateModel(
            name='EditWikidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statements_created', models.IntegerField(default=0)),
                ('statements_modified', models.IntegerField(default=0)),
                ('references_created', models.IntegerField(default=0)),
                ('references_modified', models.IntegerField(default=0)),
                ('qualifiers_created', models.IntegerField(default=0)),
                ('qualifiers_modified', models.IntegerField(default=0)),
                ('edit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editwikidata', to='contests.edit')),
            ],
            options={
                'verbose_name_plural': 'EditsWikidata',
            },
        ),
    ]
